// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Z11_LoginReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Z11_LoginReq.proto</summary>
  public static partial class Z11LoginReqReflection {

    #region Descriptor
    /// <summary>File descriptor for Z11_LoginReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Z11LoginReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJaMTFfTG9naW5SZXEucHJvdG8SAnBiIq8BCghMb2dpblJlcRIOCgZnYW1l",
            "SWQYASABKAUSEgoKcGxhdGZvcm1JZBgCIAEoBRIOCgZtb2RlSWQYAyABKAUS",
            "EQoJYWNjb3VudElkGAQgASgJEg8KB3ZlcnNpb24YBSABKAkSDgoGcm9vbUlk",
            "GAYgASgJEg0KBXRva2VuGAcgASgJEhgKEGlzQmF0dGxlVW5zZXR0bGUYCCAB",
            "KAgSEgoKYW5jaG9yTmFtZRgJIAEoCUIHWgUuLztwYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.LoginReq), global::Pb.LoginReq.Parser, new[]{ "GameId", "PlatformId", "ModeId", "AccountId", "Version", "RoomId", "Token", "IsBattleUnsettle", "AnchorName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户端登录请求
  /// </summary>
  public sealed partial class LoginReq : pb::IMessage<LoginReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginReq> _parser = new pb::MessageParser<LoginReq>(() => new LoginReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z11LoginReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginReq(LoginReq other) : this() {
      gameId_ = other.gameId_;
      platformId_ = other.platformId_;
      modeId_ = other.modeId_;
      accountId_ = other.accountId_;
      version_ = other.version_;
      roomId_ = other.roomId_;
      token_ = other.token_;
      isBattleUnsettle_ = other.isBattleUnsettle_;
      anchorName_ = other.anchorName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginReq Clone() {
      return new LoginReq(this);
    }

    /// <summary>Field number for the "gameId" field.</summary>
    public const int GameIdFieldNumber = 1;
    private int gameId_;
    /// <summary>
    /// 游戏ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameId {
      get { return gameId_; }
      set {
        gameId_ = value;
      }
    }

    /// <summary>Field number for the "platformId" field.</summary>
    public const int PlatformIdFieldNumber = 2;
    private int platformId_;
    /// <summary>
    /// 平台
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlatformId {
      get { return platformId_; }
      set {
        platformId_ = value;
      }
    }

    /// <summary>Field number for the "modeId" field.</summary>
    public const int ModeIdFieldNumber = 3;
    private int modeId_;
    /// <summary>
    /// 游戏模式/官游/野游
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ModeId {
      get { return modeId_; }
      set {
        modeId_ = value;
      }
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 4;
    private string accountId_ = "";
    /// <summary>
    /// 账号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 5;
    private string version_ = "";
    /// <summary>
    /// 版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 6;
    private string roomId_ = "";
    /// <summary>
    /// 直播间绑定码 (野游发直播路径，官方发房间id)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomId {
      get { return roomId_; }
      set {
        roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 7;
    private string token_ = "";
    /// <summary>
    /// token
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isBattleUnsettle" field.</summary>
    public const int IsBattleUnsettleFieldNumber = 8;
    private bool isBattleUnsettle_;
    /// <summary>
    /// 战斗是否未结算
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsBattleUnsettle {
      get { return isBattleUnsettle_; }
      set {
        isBattleUnsettle_ = value;
      }
    }

    /// <summary>Field number for the "anchorName" field.</summary>
    public const int AnchorNameFieldNumber = 9;
    private string anchorName_ = "";
    /// <summary>
    /// 主播的名字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AnchorName {
      get { return anchorName_; }
      set {
        anchorName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameId != other.GameId) return false;
      if (PlatformId != other.PlatformId) return false;
      if (ModeId != other.ModeId) return false;
      if (AccountId != other.AccountId) return false;
      if (Version != other.Version) return false;
      if (RoomId != other.RoomId) return false;
      if (Token != other.Token) return false;
      if (IsBattleUnsettle != other.IsBattleUnsettle) return false;
      if (AnchorName != other.AnchorName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameId != 0) hash ^= GameId.GetHashCode();
      if (PlatformId != 0) hash ^= PlatformId.GetHashCode();
      if (ModeId != 0) hash ^= ModeId.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (IsBattleUnsettle != false) hash ^= IsBattleUnsettle.GetHashCode();
      if (AnchorName.Length != 0) hash ^= AnchorName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameId);
      }
      if (PlatformId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PlatformId);
      }
      if (ModeId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ModeId);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountId);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Version);
      }
      if (RoomId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RoomId);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Token);
      }
      if (IsBattleUnsettle != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsBattleUnsettle);
      }
      if (AnchorName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AnchorName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameId);
      }
      if (PlatformId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PlatformId);
      }
      if (ModeId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ModeId);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountId);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Version);
      }
      if (RoomId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(RoomId);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Token);
      }
      if (IsBattleUnsettle != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsBattleUnsettle);
      }
      if (AnchorName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AnchorName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameId);
      }
      if (PlatformId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlatformId);
      }
      if (ModeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ModeId);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (RoomId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (IsBattleUnsettle != false) {
        size += 1 + 1;
      }
      if (AnchorName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnchorName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginReq other) {
      if (other == null) {
        return;
      }
      if (other.GameId != 0) {
        GameId = other.GameId;
      }
      if (other.PlatformId != 0) {
        PlatformId = other.PlatformId;
      }
      if (other.ModeId != 0) {
        ModeId = other.ModeId;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.RoomId.Length != 0) {
        RoomId = other.RoomId;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.IsBattleUnsettle != false) {
        IsBattleUnsettle = other.IsBattleUnsettle;
      }
      if (other.AnchorName.Length != 0) {
        AnchorName = other.AnchorName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameId = input.ReadInt32();
            break;
          }
          case 16: {
            PlatformId = input.ReadInt32();
            break;
          }
          case 24: {
            ModeId = input.ReadInt32();
            break;
          }
          case 34: {
            AccountId = input.ReadString();
            break;
          }
          case 42: {
            Version = input.ReadString();
            break;
          }
          case 50: {
            RoomId = input.ReadString();
            break;
          }
          case 58: {
            Token = input.ReadString();
            break;
          }
          case 64: {
            IsBattleUnsettle = input.ReadBool();
            break;
          }
          case 74: {
            AnchorName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameId = input.ReadInt32();
            break;
          }
          case 16: {
            PlatformId = input.ReadInt32();
            break;
          }
          case 24: {
            ModeId = input.ReadInt32();
            break;
          }
          case 34: {
            AccountId = input.ReadString();
            break;
          }
          case 42: {
            Version = input.ReadString();
            break;
          }
          case 50: {
            RoomId = input.ReadString();
            break;
          }
          case 58: {
            Token = input.ReadString();
            break;
          }
          case 64: {
            IsBattleUnsettle = input.ReadBool();
            break;
          }
          case 74: {
            AnchorName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
