// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Z12_LoginResp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Z12_LoginResp.proto</summary>
  public static partial class Z12LoginRespReflection {

    #region Descriptor
    /// <summary>File descriptor for Z12_LoginResp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Z12LoginRespReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNaMTJfTG9naW5SZXNwLnByb3RvEgJwYhoPWjBfQ29tbW9uLnByb3RvIn0K",
            "CUxvZ2luUmVzcBIOCgZlcnJNc2cYASABKAkSDgoGcm9vbUlkGAIgASgJEhIK",
            "CnNlcnZlclRpbWUYAyABKAUSIgoIYW5jaG9yREIYBCABKAsyEC5wYi5BbmNo",
            "b3JEQkluZm8SGAoQaXNCYXR0bGVVbnNldHRsZRgFIAEoCEIHWgUuLztwYmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pb.Z0CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.LoginResp), global::Pb.LoginResp.Parser, new[]{ "ErrMsg", "RoomId", "ServerTime", "AnchorDB", "IsBattleUnsettle" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 客户端登录回复
  /// </summary>
  public sealed partial class LoginResp : pb::IMessage<LoginResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginResp> _parser = new pb::MessageParser<LoginResp>(() => new LoginResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z12LoginRespReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginResp(LoginResp other) : this() {
      errMsg_ = other.errMsg_;
      roomId_ = other.roomId_;
      serverTime_ = other.serverTime_;
      anchorDB_ = other.anchorDB_ != null ? other.anchorDB_.Clone() : null;
      isBattleUnsettle_ = other.isBattleUnsettle_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginResp Clone() {
      return new LoginResp(this);
    }

    /// <summary>Field number for the "errMsg" field.</summary>
    public const int ErrMsgFieldNumber = 1;
    private string errMsg_ = "";
    /// <summary>
    ///消息code 0成功 1失败
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrMsg {
      get { return errMsg_; }
      set {
        errMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 2;
    private string roomId_ = "";
    /// <summary>
    /// 房间号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoomId {
      get { return roomId_; }
      set {
        roomId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serverTime" field.</summary>
    public const int ServerTimeFieldNumber = 3;
    private int serverTime_;
    /// <summary>
    /// 时间戳(秒)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ServerTime {
      get { return serverTime_; }
      set {
        serverTime_ = value;
      }
    }

    /// <summary>Field number for the "anchorDB" field.</summary>
    public const int AnchorDBFieldNumber = 4;
    private global::Pb.AnchorDBInfo anchorDB_;
    /// <summary>
    /// 主播数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.AnchorDBInfo AnchorDB {
      get { return anchorDB_; }
      set {
        anchorDB_ = value;
      }
    }

    /// <summary>Field number for the "isBattleUnsettle" field.</summary>
    public const int IsBattleUnsettleFieldNumber = 5;
    private bool isBattleUnsettle_;
    /// <summary>
    /// 战斗是否未结算
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsBattleUnsettle {
      get { return isBattleUnsettle_; }
      set {
        isBattleUnsettle_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrMsg != other.ErrMsg) return false;
      if (RoomId != other.RoomId) return false;
      if (ServerTime != other.ServerTime) return false;
      if (!object.Equals(AnchorDB, other.AnchorDB)) return false;
      if (IsBattleUnsettle != other.IsBattleUnsettle) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrMsg.Length != 0) hash ^= ErrMsg.GetHashCode();
      if (RoomId.Length != 0) hash ^= RoomId.GetHashCode();
      if (ServerTime != 0) hash ^= ServerTime.GetHashCode();
      if (anchorDB_ != null) hash ^= AnchorDB.GetHashCode();
      if (IsBattleUnsettle != false) hash ^= IsBattleUnsettle.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrMsg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ErrMsg);
      }
      if (RoomId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomId);
      }
      if (ServerTime != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ServerTime);
      }
      if (anchorDB_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AnchorDB);
      }
      if (IsBattleUnsettle != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsBattleUnsettle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrMsg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ErrMsg);
      }
      if (RoomId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RoomId);
      }
      if (ServerTime != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ServerTime);
      }
      if (anchorDB_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AnchorDB);
      }
      if (IsBattleUnsettle != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsBattleUnsettle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrMsg);
      }
      if (RoomId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomId);
      }
      if (ServerTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerTime);
      }
      if (anchorDB_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnchorDB);
      }
      if (IsBattleUnsettle != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginResp other) {
      if (other == null) {
        return;
      }
      if (other.ErrMsg.Length != 0) {
        ErrMsg = other.ErrMsg;
      }
      if (other.RoomId.Length != 0) {
        RoomId = other.RoomId;
      }
      if (other.ServerTime != 0) {
        ServerTime = other.ServerTime;
      }
      if (other.anchorDB_ != null) {
        if (anchorDB_ == null) {
          AnchorDB = new global::Pb.AnchorDBInfo();
        }
        AnchorDB.MergeFrom(other.AnchorDB);
      }
      if (other.IsBattleUnsettle != false) {
        IsBattleUnsettle = other.IsBattleUnsettle;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ErrMsg = input.ReadString();
            break;
          }
          case 18: {
            RoomId = input.ReadString();
            break;
          }
          case 24: {
            ServerTime = input.ReadInt32();
            break;
          }
          case 34: {
            if (anchorDB_ == null) {
              AnchorDB = new global::Pb.AnchorDBInfo();
            }
            input.ReadMessage(AnchorDB);
            break;
          }
          case 40: {
            IsBattleUnsettle = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ErrMsg = input.ReadString();
            break;
          }
          case 18: {
            RoomId = input.ReadString();
            break;
          }
          case 24: {
            ServerTime = input.ReadInt32();
            break;
          }
          case 34: {
            if (anchorDB_ == null) {
              AnchorDB = new global::Pb.AnchorDBInfo();
            }
            input.ReadMessage(AnchorDB);
            break;
          }
          case 40: {
            IsBattleUnsettle = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
