// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Z22_UpdatePlayerStatusNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Z22_UpdatePlayerStatusNotify.proto</summary>
  public static partial class Z22UpdatePlayerStatusNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for Z22_UpdatePlayerStatusNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Z22UpdatePlayerStatusNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJaMjJfVXBkYXRlUGxheWVyU3RhdHVzTm90aWZ5LnByb3RvEgJwYhoPWjBf",
            "Q29tbW9uLnByb3RvIlIKGFVwZGF0ZVBsYXllclN0YXR1c05vdGlmeRI2ChZV",
            "cGRhdGVQbGF5ZXJTdGF0dXNMaXN0GAEgAygLMhYucGIuVXBkYXRlUGxheWVy",
            "U3RhdHVzIooBChJVcGRhdGVQbGF5ZXJTdGF0dXMSDgoGb3BlbklkGAEgASgJ",
            "EhYKDnN0YXRlU3RhcnRUaW1lGAIgASgDEiQKC3BsYXllclN0YXRlGAMgASgO",
            "Mg8ucGIuUGxheWVyU3RhdGUSJgoKQmF0dGxlRmlzaBgEIAEoCzISLnBiLkJh",
            "dHRsZUZpc2hJbmZvQgdaBS4vO3BiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pb.Z0CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.UpdatePlayerStatusNotify), global::Pb.UpdatePlayerStatusNotify.Parser, new[]{ "UpdatePlayerStatusList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.UpdatePlayerStatus), global::Pb.UpdatePlayerStatus.Parser, new[]{ "OpenId", "StateStartTime", "PlayerState", "BattleFish" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 更新玩家的状态
  /// </summary>
  public sealed partial class UpdatePlayerStatusNotify : pb::IMessage<UpdatePlayerStatusNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdatePlayerStatusNotify> _parser = new pb::MessageParser<UpdatePlayerStatusNotify>(() => new UpdatePlayerStatusNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdatePlayerStatusNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z22UpdatePlayerStatusNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerStatusNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerStatusNotify(UpdatePlayerStatusNotify other) : this() {
      updatePlayerStatusList_ = other.updatePlayerStatusList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerStatusNotify Clone() {
      return new UpdatePlayerStatusNotify(this);
    }

    /// <summary>Field number for the "UpdatePlayerStatusList" field.</summary>
    public const int UpdatePlayerStatusListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Pb.UpdatePlayerStatus> _repeated_updatePlayerStatusList_codec
        = pb::FieldCodec.ForMessage(10, global::Pb.UpdatePlayerStatus.Parser);
    private readonly pbc::RepeatedField<global::Pb.UpdatePlayerStatus> updatePlayerStatusList_ = new pbc::RepeatedField<global::Pb.UpdatePlayerStatus>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.UpdatePlayerStatus> UpdatePlayerStatusList {
      get { return updatePlayerStatusList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdatePlayerStatusNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdatePlayerStatusNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updatePlayerStatusList_.Equals(other.updatePlayerStatusList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updatePlayerStatusList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      updatePlayerStatusList_.WriteTo(output, _repeated_updatePlayerStatusList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      updatePlayerStatusList_.WriteTo(ref output, _repeated_updatePlayerStatusList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += updatePlayerStatusList_.CalculateSize(_repeated_updatePlayerStatusList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdatePlayerStatusNotify other) {
      if (other == null) {
        return;
      }
      updatePlayerStatusList_.Add(other.updatePlayerStatusList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updatePlayerStatusList_.AddEntriesFrom(input, _repeated_updatePlayerStatusList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            updatePlayerStatusList_.AddEntriesFrom(ref input, _repeated_updatePlayerStatusList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpdatePlayerStatus : pb::IMessage<UpdatePlayerStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdatePlayerStatus> _parser = new pb::MessageParser<UpdatePlayerStatus>(() => new UpdatePlayerStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdatePlayerStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z22UpdatePlayerStatusNotifyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerStatus(UpdatePlayerStatus other) : this() {
      openId_ = other.openId_;
      stateStartTime_ = other.stateStartTime_;
      playerState_ = other.playerState_;
      battleFish_ = other.battleFish_ != null ? other.battleFish_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerStatus Clone() {
      return new UpdatePlayerStatus(this);
    }

    /// <summary>Field number for the "openId" field.</summary>
    public const int OpenIdFieldNumber = 1;
    private string openId_ = "";
    /// <summary>
    /// openId
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpenId {
      get { return openId_; }
      set {
        openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stateStartTime" field.</summary>
    public const int StateStartTimeFieldNumber = 2;
    private long stateStartTime_;
    /// <summary>
    /// 状态开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StateStartTime {
      get { return stateStartTime_; }
      set {
        stateStartTime_ = value;
      }
    }

    /// <summary>Field number for the "playerState" field.</summary>
    public const int PlayerStateFieldNumber = 3;
    private global::Pb.PlayerState playerState_ = global::Pb.PlayerState.Free;
    /// <summary>
    ///  玩家的状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PlayerState PlayerState {
      get { return playerState_; }
      set {
        playerState_ = value;
      }
    }

    /// <summary>Field number for the "BattleFish" field.</summary>
    public const int BattleFishFieldNumber = 4;
    private global::Pb.BattleFishInfo battleFish_;
    /// <summary>
    ///------------甩干后的状态有这个----
    /// 准备要掉的鱼
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.BattleFishInfo BattleFish {
      get { return battleFish_; }
      set {
        battleFish_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdatePlayerStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdatePlayerStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OpenId != other.OpenId) return false;
      if (StateStartTime != other.StateStartTime) return false;
      if (PlayerState != other.PlayerState) return false;
      if (!object.Equals(BattleFish, other.BattleFish)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
      if (StateStartTime != 0L) hash ^= StateStartTime.GetHashCode();
      if (PlayerState != global::Pb.PlayerState.Free) hash ^= PlayerState.GetHashCode();
      if (battleFish_ != null) hash ^= BattleFish.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OpenId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OpenId);
      }
      if (StateStartTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StateStartTime);
      }
      if (PlayerState != global::Pb.PlayerState.Free) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PlayerState);
      }
      if (battleFish_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BattleFish);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OpenId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OpenId);
      }
      if (StateStartTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StateStartTime);
      }
      if (PlayerState != global::Pb.PlayerState.Free) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PlayerState);
      }
      if (battleFish_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BattleFish);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OpenId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpenId);
      }
      if (StateStartTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StateStartTime);
      }
      if (PlayerState != global::Pb.PlayerState.Free) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerState);
      }
      if (battleFish_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleFish);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdatePlayerStatus other) {
      if (other == null) {
        return;
      }
      if (other.OpenId.Length != 0) {
        OpenId = other.OpenId;
      }
      if (other.StateStartTime != 0L) {
        StateStartTime = other.StateStartTime;
      }
      if (other.PlayerState != global::Pb.PlayerState.Free) {
        PlayerState = other.PlayerState;
      }
      if (other.battleFish_ != null) {
        if (battleFish_ == null) {
          BattleFish = new global::Pb.BattleFishInfo();
        }
        BattleFish.MergeFrom(other.BattleFish);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OpenId = input.ReadString();
            break;
          }
          case 16: {
            StateStartTime = input.ReadInt64();
            break;
          }
          case 24: {
            PlayerState = (global::Pb.PlayerState) input.ReadEnum();
            break;
          }
          case 34: {
            if (battleFish_ == null) {
              BattleFish = new global::Pb.BattleFishInfo();
            }
            input.ReadMessage(BattleFish);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OpenId = input.ReadString();
            break;
          }
          case 16: {
            StateStartTime = input.ReadInt64();
            break;
          }
          case 24: {
            PlayerState = (global::Pb.PlayerState) input.ReadEnum();
            break;
          }
          case 34: {
            if (battleFish_ == null) {
              BattleFish = new global::Pb.BattleFishInfo();
            }
            input.ReadMessage(BattleFish);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
