// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Z23_UpdateBattleFishNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Z23_UpdateBattleFishNotify.proto</summary>
  public static partial class Z23UpdateBattleFishNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for Z23_UpdateBattleFishNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Z23UpdateBattleFishNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBaMjNfVXBkYXRlQmF0dGxlRmlzaE5vdGlmeS5wcm90bxICcGIiTAoWVXBk",
            "YXRlQmF0dGxlRmlzaE5vdGlmeRIyChRVcGRhdGVCYXR0bGVGaXNoTGlzdBgB",
            "IAMoCzIULnBiLlVwZGF0ZUJhdHRsZUZpc2gitAEKEFVwZGF0ZUJhdHRsZUZp",
            "c2gSDgoGb3BlbklkGAEgASgJEhoKEmJhdHRsZUR1cmF0aW9uTWlsbBgCIAEo",
            "AxIXCg9hdHRhY2tTdGFydFRpbWUYAyABKAMSDQoFYmxvb2QYBCABKAESEQoJ",
            "ZGVkdWN0aW9uGAUgASgBEhIKCmlzQ3JpdGljYWwYBiABKAgSEQoJaXNDb3B5",
            "TmV0GAcgASgIEhIKCmlzRmlyc3RIaXQYCCABKAhCB1oFLi87cGJiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.UpdateBattleFishNotify), global::Pb.UpdateBattleFishNotify.Parser, new[]{ "UpdateBattleFishList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.UpdateBattleFish), global::Pb.UpdateBattleFish.Parser, new[]{ "OpenId", "BattleDurationMill", "AttackStartTime", "Blood", "Deduction", "IsCritical", "IsCopyNet", "IsFirstHit" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 更新玩家战斗的信息
  /// </summary>
  public sealed partial class UpdateBattleFishNotify : pb::IMessage<UpdateBattleFishNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateBattleFishNotify> _parser = new pb::MessageParser<UpdateBattleFishNotify>(() => new UpdateBattleFishNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateBattleFishNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z23UpdateBattleFishNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateBattleFishNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateBattleFishNotify(UpdateBattleFishNotify other) : this() {
      updateBattleFishList_ = other.updateBattleFishList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateBattleFishNotify Clone() {
      return new UpdateBattleFishNotify(this);
    }

    /// <summary>Field number for the "UpdateBattleFishList" field.</summary>
    public const int UpdateBattleFishListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Pb.UpdateBattleFish> _repeated_updateBattleFishList_codec
        = pb::FieldCodec.ForMessage(10, global::Pb.UpdateBattleFish.Parser);
    private readonly pbc::RepeatedField<global::Pb.UpdateBattleFish> updateBattleFishList_ = new pbc::RepeatedField<global::Pb.UpdateBattleFish>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.UpdateBattleFish> UpdateBattleFishList {
      get { return updateBattleFishList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateBattleFishNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateBattleFishNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updateBattleFishList_.Equals(other.updateBattleFishList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updateBattleFishList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      updateBattleFishList_.WriteTo(output, _repeated_updateBattleFishList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      updateBattleFishList_.WriteTo(ref output, _repeated_updateBattleFishList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += updateBattleFishList_.CalculateSize(_repeated_updateBattleFishList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateBattleFishNotify other) {
      if (other == null) {
        return;
      }
      updateBattleFishList_.Add(other.updateBattleFishList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updateBattleFishList_.AddEntriesFrom(input, _repeated_updateBattleFishList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            updateBattleFishList_.AddEntriesFrom(ref input, _repeated_updateBattleFishList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpdateBattleFish : pb::IMessage<UpdateBattleFish>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateBattleFish> _parser = new pb::MessageParser<UpdateBattleFish>(() => new UpdateBattleFish());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateBattleFish> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z23UpdateBattleFishNotifyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateBattleFish() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateBattleFish(UpdateBattleFish other) : this() {
      openId_ = other.openId_;
      battleDurationMill_ = other.battleDurationMill_;
      attackStartTime_ = other.attackStartTime_;
      blood_ = other.blood_;
      deduction_ = other.deduction_;
      isCritical_ = other.isCritical_;
      isCopyNet_ = other.isCopyNet_;
      isFirstHit_ = other.isFirstHit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateBattleFish Clone() {
      return new UpdateBattleFish(this);
    }

    /// <summary>Field number for the "openId" field.</summary>
    public const int OpenIdFieldNumber = 1;
    private string openId_ = "";
    /// <summary>
    /// openId
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpenId {
      get { return openId_; }
      set {
        openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "battleDurationMill" field.</summary>
    public const int BattleDurationMillFieldNumber = 2;
    private long battleDurationMill_;
    /// <summary>
    /// 战斗剩余的持续时间 （毫秒）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BattleDurationMill {
      get { return battleDurationMill_; }
      set {
        battleDurationMill_ = value;
      }
    }

    /// <summary>Field number for the "attackStartTime" field.</summary>
    public const int AttackStartTimeFieldNumber = 3;
    private long attackStartTime_;
    /// <summary>
    /// 上次战斗攻击开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AttackStartTime {
      get { return attackStartTime_; }
      set {
        attackStartTime_ = value;
      }
    }

    /// <summary>Field number for the "blood" field.</summary>
    public const int BloodFieldNumber = 4;
    private double blood_;
    /// <summary>
    /// 当前血量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Blood {
      get { return blood_; }
      set {
        blood_ = value;
      }
    }

    /// <summary>Field number for the "deduction" field.</summary>
    public const int DeductionFieldNumber = 5;
    private double deduction_;
    /// <summary>
    /// 当前扣血
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Deduction {
      get { return deduction_; }
      set {
        deduction_ = value;
      }
    }

    /// <summary>Field number for the "isCritical" field.</summary>
    public const int IsCriticalFieldNumber = 6;
    private bool isCritical_;
    /// <summary>
    /// 当前是否暴击
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCritical {
      get { return isCritical_; }
      set {
        isCritical_ = value;
      }
    }

    /// <summary>Field number for the "isCopyNet" field.</summary>
    public const int IsCopyNetFieldNumber = 7;
    private bool isCopyNet_;
    /// <summary>
    /// 是否抄网
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCopyNet {
      get { return isCopyNet_; }
      set {
        isCopyNet_ = value;
      }
    }

    /// <summary>Field number for the "isFirstHit" field.</summary>
    public const int IsFirstHitFieldNumber = 8;
    private bool isFirstHit_;
    /// <summary>
    /// 是否首伤
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsFirstHit {
      get { return isFirstHit_; }
      set {
        isFirstHit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateBattleFish);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateBattleFish other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OpenId != other.OpenId) return false;
      if (BattleDurationMill != other.BattleDurationMill) return false;
      if (AttackStartTime != other.AttackStartTime) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Blood, other.Blood)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Deduction, other.Deduction)) return false;
      if (IsCritical != other.IsCritical) return false;
      if (IsCopyNet != other.IsCopyNet) return false;
      if (IsFirstHit != other.IsFirstHit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
      if (BattleDurationMill != 0L) hash ^= BattleDurationMill.GetHashCode();
      if (AttackStartTime != 0L) hash ^= AttackStartTime.GetHashCode();
      if (Blood != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Blood);
      if (Deduction != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Deduction);
      if (IsCritical != false) hash ^= IsCritical.GetHashCode();
      if (IsCopyNet != false) hash ^= IsCopyNet.GetHashCode();
      if (IsFirstHit != false) hash ^= IsFirstHit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OpenId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OpenId);
      }
      if (BattleDurationMill != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(BattleDurationMill);
      }
      if (AttackStartTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AttackStartTime);
      }
      if (Blood != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Blood);
      }
      if (Deduction != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Deduction);
      }
      if (IsCritical != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsCritical);
      }
      if (IsCopyNet != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsCopyNet);
      }
      if (IsFirstHit != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsFirstHit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OpenId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OpenId);
      }
      if (BattleDurationMill != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(BattleDurationMill);
      }
      if (AttackStartTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AttackStartTime);
      }
      if (Blood != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Blood);
      }
      if (Deduction != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Deduction);
      }
      if (IsCritical != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsCritical);
      }
      if (IsCopyNet != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsCopyNet);
      }
      if (IsFirstHit != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsFirstHit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OpenId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpenId);
      }
      if (BattleDurationMill != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BattleDurationMill);
      }
      if (AttackStartTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AttackStartTime);
      }
      if (Blood != 0D) {
        size += 1 + 8;
      }
      if (Deduction != 0D) {
        size += 1 + 8;
      }
      if (IsCritical != false) {
        size += 1 + 1;
      }
      if (IsCopyNet != false) {
        size += 1 + 1;
      }
      if (IsFirstHit != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateBattleFish other) {
      if (other == null) {
        return;
      }
      if (other.OpenId.Length != 0) {
        OpenId = other.OpenId;
      }
      if (other.BattleDurationMill != 0L) {
        BattleDurationMill = other.BattleDurationMill;
      }
      if (other.AttackStartTime != 0L) {
        AttackStartTime = other.AttackStartTime;
      }
      if (other.Blood != 0D) {
        Blood = other.Blood;
      }
      if (other.Deduction != 0D) {
        Deduction = other.Deduction;
      }
      if (other.IsCritical != false) {
        IsCritical = other.IsCritical;
      }
      if (other.IsCopyNet != false) {
        IsCopyNet = other.IsCopyNet;
      }
      if (other.IsFirstHit != false) {
        IsFirstHit = other.IsFirstHit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OpenId = input.ReadString();
            break;
          }
          case 16: {
            BattleDurationMill = input.ReadInt64();
            break;
          }
          case 24: {
            AttackStartTime = input.ReadInt64();
            break;
          }
          case 33: {
            Blood = input.ReadDouble();
            break;
          }
          case 41: {
            Deduction = input.ReadDouble();
            break;
          }
          case 48: {
            IsCritical = input.ReadBool();
            break;
          }
          case 56: {
            IsCopyNet = input.ReadBool();
            break;
          }
          case 64: {
            IsFirstHit = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            OpenId = input.ReadString();
            break;
          }
          case 16: {
            BattleDurationMill = input.ReadInt64();
            break;
          }
          case 24: {
            AttackStartTime = input.ReadInt64();
            break;
          }
          case 33: {
            Blood = input.ReadDouble();
            break;
          }
          case 41: {
            Deduction = input.ReadDouble();
            break;
          }
          case 48: {
            IsCritical = input.ReadBool();
            break;
          }
          case 56: {
            IsCopyNet = input.ReadBool();
            break;
          }
          case 64: {
            IsFirstHit = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
