// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Z4_TipsNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Z4_TipsNotify.proto</summary>
  public static partial class Z4TipsNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for Z4_TipsNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Z4TipsNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNaNF9UaXBzTm90aWZ5LnByb3RvEgJwYiI3CgpUaXBzTm90aWZ5Eg4KBnRp",
            "cE1zZxgBIAEoCRIZCgR0eXBlGAIgASgOMgsucGIuVGlwVHlwZSpTCgdUaXBU",
            "eXBlEgoKBk5vcm1hbBAAEgoKBk5vdGljZRABEgwKCFJvb21Sb2xsEAISDwoL",
            "Um9vbU1hcnF1ZWUQAxIRCg1TZXJ2ZXJNYXJxdWVlEARCB1oFLi87cGJiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.TipType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.TipsNotify), global::Pb.TipsNotify.Parser, new[]{ "TipMsg", "Type" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TipType {
    [pbr::OriginalName("Normal")] Normal = 0,
    /// <summary>
    /// 公告
    /// </summary>
    [pbr::OriginalName("Notice")] Notice = 1,
    /// <summary>
    ///2直播间滚条
    /// </summary>
    [pbr::OriginalName("RoomRoll")] RoomRoll = 2,
    /// <summary>
    ///直播间的跑马灯
    /// </summary>
    [pbr::OriginalName("RoomMarquee")] RoomMarquee = 3,
    /// <summary>
    /// 全服的跑马灯
    /// </summary>
    [pbr::OriginalName("ServerMarquee")] ServerMarquee = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 提示(一般错误)
  /// </summary>
  public sealed partial class TipsNotify : pb::IMessage<TipsNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TipsNotify> _parser = new pb::MessageParser<TipsNotify>(() => new TipsNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TipsNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Z4TipsNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TipsNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TipsNotify(TipsNotify other) : this() {
      tipMsg_ = other.tipMsg_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TipsNotify Clone() {
      return new TipsNotify(this);
    }

    /// <summary>Field number for the "tipMsg" field.</summary>
    public const int TipMsgFieldNumber = 1;
    private string tipMsg_ = "";
    /// <summary>
    /// 错误信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TipMsg {
      get { return tipMsg_; }
      set {
        tipMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Pb.TipType type_ = global::Pb.TipType.Normal;
    /// <summary>
    /// 0普通 1公告 2本直播间滚条 3.本直播间的跑马灯  4.全服的跑马灯
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.TipType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TipsNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TipsNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TipMsg != other.TipMsg) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TipMsg.Length != 0) hash ^= TipMsg.GetHashCode();
      if (Type != global::Pb.TipType.Normal) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TipMsg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TipMsg);
      }
      if (Type != global::Pb.TipType.Normal) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TipMsg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TipMsg);
      }
      if (Type != global::Pb.TipType.Normal) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TipMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TipMsg);
      }
      if (Type != global::Pb.TipType.Normal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TipsNotify other) {
      if (other == null) {
        return;
      }
      if (other.TipMsg.Length != 0) {
        TipMsg = other.TipMsg;
      }
      if (other.Type != global::Pb.TipType.Normal) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TipMsg = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Pb.TipType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TipMsg = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Pb.TipType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
